### ISSUE TITLE
Test: Integration test to claim `d2dBal` rewards on `kovan`

### ISSUE THREAD

**Issue by BritikovKI** [PrimeDAO/pools-contracts#122]
## Status quo

It makes sense to check if staked d2d LP tokens return some rewards.

## Acceptance criteria

- [x] Add pool, and deposit LP tokens through `Controller`
- [x] Call `earmarkRewards` function  in `Controller` for that pool. Supposedly it should produce some rewards after a week-two of staking, but not sure how it will work here
- [x] Check fees distribution for the rewards

**Comment by bxmmm1** [comment]
[EarmarkRewards works](https://kovan.etherscan.io/tx/0x7ddaa4d52e0838c9d195609478f376b7a88b76626fb5be732e71b81d4999ebf5), and reward distribution is how it should be.
Default values are 2.5% for profit fees, 10% platform fee

We deposit LP tokens to the pool, and after some time we call earmarkRewards for that pool, and we get the following:

We mint ~229.67 BAL as a reward
~5.74 (2.5% goes to Prime multisig)
~ 22.967 (10% goes to treasury)
the remainder goes to the rewards contract
