### ISSUE TITLE
Test: Using integration test, try to withdraw staked funds from veBal

### ISSUE THREAD

**Issue by BritikovKI** [PrimeDAO/pools-contracts#124]
## Status quo

As one of the features we've added a possibility to withdraw wethBal after stake deadline is over and put contract on pause

## Acceptance criteria

- [ ] Deposit some wethBal to the contract
- [ ] "Wait" for a year and try to withdraw the funds after the year.

**Comment by bxmmm1** [comment]
In conflict with audit and #160
