### ISSUE TITLE
Chore: Check return values of any transfers to unknown ERC20's / switch to safeTransfer

### ISSUE THREAD

**Issue by ftperez11** [PrimeDAO/pools-contracts#146]
## Status quo
Cannot expect transfer calls to revert on failure, need to check the return value (Transfer & TransferFrom)

## Acceptance criteria

- [x] Leave as is and check return values from transfer and transferFrom 
- [ ] Change to using safeTransfer and safeTransferFrom 
- [x] Make the mentioned updates in Controller (in earmarkFees), ExtraRewardStash and VirtualBalanceReward contracts

**Comment by bxmmm1** [comment]
Tokens that we create, Balancer tokens don't need safeTransfer.
Various reward tokens can cause problems so for those interactions we should check the transfer status.

**Comment by bxmmm1** [comment]
Splitting this out from the `Audit fixes` branch into a separate PR

**Comment by bxmmm1** [comment]
Switched to SafeTransfer for risky tokens
