### ISSUE TITLE
Chore: Add functionality to allow admin account to remove single & all extra rewards from the pool

### ISSUE THREAD

**Issue by ftperez11** [PrimeDAO/pools-contracts#150]
## Status quo
 -  Extra rewards currently has the ability to permanently paralyze the pool
## Acceptance criteria

- [x] Allow removing a single or all extra rewards from the pool functionality by an admin account

**Comment by bxmmm1** [comment]
Multisig (owner of Controller.sol) has the ability to remove reward tokens BaseRewardPool contracts
