### ISSUE TITLE
Chore: BalDepositor - update deposit function so deposited tokens are always automatically staked

### ISSUE THREAD

**Issue by ftperez11** [PrimeDAO/pools-contracts#156]
## Status quo
Currently since Deposit function takes in a _stakeAddress as an argument, the caller can provide any address. This goes against our intention of all minted d2dbal automatically being staked to Rewards contract

## Acceptance criteria

- [ ] Remove the _stakeAddress argument from the function signature, and instead automatically stake the D2DBal tokens in the correct Rewards contract

**Comment by bxmmm1** [comment]
This would introduce another state variable, and increase gas cost. @BritikovKI wyt?

**Comment by BritikovKI** [comment]
Another state variable with address will be just a little bit pricier, but this will save us some gas in the long run, so I think we should remove it...
Just add a functionality to possibly change it as well(onlyOwner)

**Comment by bxmmm1** [comment]
> Another state variable with address will be just a little bit pricier, but this will save us some gas in the long run, so I think we should remove it... Just add a functionality to possibly change it as well(onlyOwner)

I'll interpret this comment as 'leave as is'  😃 because in our current implementation we have it like that
