### ISSUE TITLE
Chore: Controller.sol - update logic when shutting down a pool to remove all remaining rewards from gauge

### ISSUE THREAD

**Issue by ftperez11** [PrimeDAO/pools-contracts#159]
## Status quo
The shutdown action does not claim the remaining reward that might exist in the gauge. After the pool is shut down it is impossible to claim the rewards, because the earmarkRewards function becomes disabled.

## Acceptance criteria

- [x] Call earmarkRewards in the shutdownPool function
- [ ] Call earmarkRewards in the shutdownSystem function

**Comment by bxmmm1** [comment]
We've decided to not do this for shutdown system because of a loop. I've simulated a transaction for Convex shutDownSystem, and it would fail (out of gas). We've changed logic a bit. 
In worst case scenario, script would send `bulkPoolShutdown` transactions + shutdown system
