### ISSUE TITLE
Chore: Controller.sol - Implement auto re-staking, or change specifications related to this

### ISSUE THREAD

**Issue by ftperez11** [PrimeDAO/pools-contracts#161]
## Status quo
***Need to discuss how to address this and will update acceptance criteria***
Currently there is no automatic mechanism that reinvests a percentage of the BAL tokens towards staking for veBAL

## Acceptance criteria

- [ ] Implement auto restaking mechanism

**Comment by bxmmm1** [comment]
We aren't implementing this, so it is a change of specifications
