### ISSUE TITLE
Chore: Controller.sol - Update logic in earmarkRewards function to preserve and claim all rewards

### ISSUE THREAD

**Issue by ftperez11** [PrimeDAO/pools-contracts#162]
## Status quo
When shutting down a pool with shutdownSystem, If the call to withdrawAll fails, the tokens will still be deposited and earning rewards in the gauge, but it will not be possible to claim these rewards

## Acceptance criteria

- [x]  Remove the isNotShutDown modifier from the earmarkRewards function.

**Comment by bxmmm1** [comment]
resolved in #145
