### ISSUE TITLE
Chore: ExtraRewardStash.sol - update control functionality so owner of Controller can remove/ disable reward tokens from the tokenList.

### ISSUE THREAD

**Issue by ftperez11** [PrimeDAO/pools-contracts#164]
## Status quo
 Extra rewards in a pool become unavailable if one token transfer fails, since this function loops through all tokens in tokenList of ExtraRewardStash. 

## Acceptance criteria

- [x] Create functionality to allow the owner of the Controller to remove/ disable reward tokens from the tokenList.

**Comment by bxmmm1** [comment]
Fixed in #145
