### ISSUE TITLE
Chore: VoterProxy.sol - remove unused functionality

### ISSUE THREAD

**Issue by ftperez11** [PrimeDAO/pools-contracts#165]
## Status quo
The withdraw(IERC20 _asset) function can only be called by an address that has stashAccess set to true. However, the ExtraRewardStash contract, which is the only contract granted stash access, does not contain any code to call this function. 

## Acceptance criteria

- [x] Remove the  withdraw(IERC20 _asset) function. 
- [x] Also remove related stash access functionality, such as grantStashAccess

**Comment by bxmmm1** [comment]
resolved in #145
