### ISSUE TITLE
Chore: StashFactory.sol - Remove proxy factory, use OZ's clones library

### ISSUE THREAD

**Issue by ftperez11** [PrimeDAO/pools-contracts#166]
## Status quo
The proxy factory used by the stash factory to create clones could be replaced with a call to the OpenZeppelin Clones library function Clones.clone.

## Acceptance criteria

- [ ] Delete the ProxyFactory.sol and replace its use with the OpenZeppelin Clones library

**Comment by bxmmm1** [comment]
I'd skip this one, as we're copy-pasting the code from that lib. Using it will increase the deployment gas cost
