### ISSUE TITLE
Chore: remove flow to lock WETH/BAL for a user in `BalDepositor`

### ISSUE THREAD

**Issue by BritikovKI** [PrimeDAO/pools-contracts#53]
## Status quo
Currently there is a way for user to transfer funds to the `BalDepositor`, so they'll be locked by someone else in veBal, we don't need this flow.

## Acceptance criteria
- [ ] incentiveBal variable and its usages are removed.
- [ ] lockIncentive and its usages are removed.
- [ ] setFees and setFeeManager functions are removed.
- [ ] feeManager is removed, there are no fees on depositing funds.
- [ ] lockBalancer function is removed. **(only external)**

**Comment by bxmmm1** [comment]
Outdated, closing
